id: "mongosController"
kind: "ReplicationController"
apiVersion: "v1beta1"
desiredState: 
  replicas: 3
  replicaSelector: 
    name: "mongos"
  podTemplate: 
    desiredState: 
      manifest: 
        version: "v1beta1"
        id: "mongosController"
        containers: 
          - name: "mongos"
            image: "vsheffer/mongo:mongos"
            command: [ 
              "/usr/local/bin/mongos",
              "--configdb=mongoconfig.default.bhnetwork.local"
            ]
            cpu: 100
            ports: 
              - containerPort: 27017
                hostPort: 27017
    labels: 
      name: "mongos"
labels: 
  name: "mongos"
