id: mongoarb{REPLICA_SET_ID}
kind: ReplicationController
apiVersion: v1beta2
labels: 
  type: mongoarb
  replica-set: {REPLICA_SET_ID}
desiredState: 
  replicas: 1
  replicaSelector: 
      type: mongoarb
      replica-set: {REPLICA_SET_ID}
  podTemplate: 
    labels: 
      type: mongoarb
      replica-set: {REPLICA_SET_ID}
    desiredState: 
      manifest: 
        version: "v1beta1"
        id: "mongoarb{REPLICA_SET_ID}"
        containers: 
          - name: "mongoarb"
            image: "vsheffer/mongo:mongo-arbiter"
            command: [ 
              "/usr/local/bin/mongod",
              "--replSet {REPLICA_SET_ID}"
            ]
            cpu: 100
            ports: 
              - containerPort: 27017
                hostPort: {HOST_PORT}

